# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Fazendo login no ECR...      
#       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 011528257712.dkr.ecr.us-east-1.amazonaws.com
#       - REPOSITORY_URI=011528257712.dkr.ecr.us-east-1.amazonaws.com/meddiflux
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build iniciado em `date`
#       - echo Gerando imagem da MEDDIFLUX...
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build finalizado com sucesso em `date`
#       - echo Fazendo push da imagem para o ECR...
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Gerando artefato da imagem para o ECS
#       - printf '[{"name":"bia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#   files: imagedefinitions.json
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fazendo login no ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 011528257712.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=011528257712.dkr.ecr.us-east-1.amazonaws.com/meddiflux
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Build iniciado em $(date)"
      - echo "Gerando imagem da MEDDIFLUX..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build finalizado com sucesso em $(date)"
      - echo "Fazendo push da imagem para o ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Gerando artefatos para o Elastic Beanstalk..."
      - printf '[{"name":"meddiflux","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      # Criando a estrutura de arquivos para o EB
      - mkdir -p .ebextensions
      - echo "Preparando arquivos para deployment..."
      - |
        cat > Dockerrun.aws.json << 'EOF'
        {
          "AWSEBDockerrunVersion": "3",
          "Image": {
            "Name": "${REPOSITORY_URI}:${IMAGE_TAG}",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 3000,
              "HostPort": 80
            }
          ]
        }
        EOF
      - zip -r deployment.zip Dockerrun.aws.json docker-compose.yml .ebextensions/

artifacts:
  files:
    - deployment.zip
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - '/root/.docker/**/*'
